baseURL = 'https://sdnsondo.github.io/'
languageCode = 'en'
title = 'SD Negeri Sondo'
theme = 'hugo-theme-chunky-poster'

paginate = 2
copyright = "Copyright © 2020–2021, SD Negeri Sondo all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "visi-misi"
    name = "Visi Misi"
    url = "/visi-misi/"
    weight = 2
  [[menu.main]]
    identifier = "tentang-kami"
    name = "Tentang Kami"
    url = "/tentang-kami/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"


[params]
  author = "Admin"
  description = "Unggul Dalam Mutu, Teruji Dalam Prestasi."
  homepageImage = "/images/homepage-image.png"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false

  customCSS = []
  customJS = []
  
  [params.prismJS]
    enable = true
    theme = "okaidia"

[markup]
  [markup.highlight]
    codeFences = false